spring:
  liquibase:
    change-log: classpath:db/changelog.sql
  datasource:
    password: demo_password
    username: demo_user
    url: jdbc:postgresql://postgres:5432/demo_db
  threads:
    virtual:
      enabled: true

spam-email:
  address: foo@bar.com
  cron: "0 0 10 * * *"
